services:

  mysql-db-siPmu:
    container_name: mysql-db-siPmu
    ports:
      - "3306:3306"
    volumes:
      - "db_data:/var/lib/mysql"
    extends:
      file: common-config.yml
      service: mysql-db-config

  kafka:
    image: docker.io/bitnami/kafka:3.8
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--list" ]
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 60s
    networks:
      - mamadou4bah

  si-pmu-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: si-pmu-app
    restart: always
    depends_on:
      mysql-db-siPmu:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "8097:8099"
    healthcheck:
      test: "curl --fail --silent localhost:8099/actuator/health/readiness | grep UP || exit 1"
      interval: 60s
      timeout: 5s
      retries: 60
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: si-pmu-app
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db-siPmu:3306/siPmuDb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SERVER_SERVLET_CONTEXT-PATH: /si-pmu
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "kafka:9092"
    networks:
      - mamadou4bah

networks:
  mamadou4bah:
    driver: "bridge"

volumes:
  db_data:
  kafka_data: