global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'si-pmu-app'
    metrics_path: '/si-pmu/actuator/prometheus'
    static_configs:
      - targets: [ 'si-pmu-app:8099' ]
  
